version: '3.3'

services:
  build-game-linux:
    image : ioribranford/godot-docker:3.1.1
    volumes:
      - './game:/build/src'
      - './build:/build/output'
    environment:
      - /bin/bash
    command: godot --export 'Linux/X11' /build/output/test --path /build/src

  build-game-html:
    image : ioribranford/godot-docker:3.1.1
    volumes:
      - './game:/build/src'
      - './build:/build/output'
    environment:
      - /bin/bash
    command: godot --export-debug 'HTML5' /build/output/test.html --path /build/src

  run-site:
    image : darcemontv/node_astralys
    volumes:
      - './bdd:/bdd'
      - './build:/build'
    ports :
      - 8080:8080

